In [1]:
import pandas as pd
from db_utils import db_conectar  # usamos pyodbc para Silver (explicar porque en la presentacion)

conn = db_conectar()

In [2]:
#Probamos conexion de bd y verificamos las tablas   
query1 = "SELECT * FROM Bronce.Sysarmy_2023_1"
query2 = "SELECT * FROM Bronce.Sysarmy_2023_2"

# Leemos las tablas en dataframes
df1 = pd.read_sql(query1, conn)
df2 = pd.read_sql(query2, conn)

# Verificamos la cantidad de filas
print("Filas Sysarmy 2023 pt1:", len(df1))
print("Filas Sysarmy 2023 p2:", len(df2))

C:\Users\54112\AppData\Local\Temp\ipykernel_23480\300873053.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql(query1, conn)
C:\Users\54112\AppData\Local\Temp\ipykernel_23480\300873053.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(query2, conn)

Filas Sysarmy 2023 pt1: 5767
Filas Sysarmy 2023 p2: 5422

In [3]:
renombre_col = {
    "donde_estas_trabajando": "provincia",
    "dedicacion": "jornada",
    "tipo_de_contrato": "tipo_contrato",
    "ultimo_salario_mensual_o_retiro_neto_en_tu_moneda_local": "salario_neto_ars",
    "salario_neto_ars": "salario_neto_ars",
    "sueldo_dolarizado": "sueldo_dolarizado",
    "si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron": "valor_dolar",
    "tengo_edad": "edad",
    "genero": "genero",
    "me_identifico_genero": "genero",
    "seniority": "seniority",
    "recibis_algun_tipo_de_bono": "bono",
    "bono": "bono",
    "actualizacion_salarial": "actualizacion_salarial",
    "tuviste_actualizaciones_de_tus_ingresos_laborales_durante_2022": "actualizacion_salarial",
    "tuviste_actualizaciones_de_tus_ingresos_laborales_durante_2023": "actualizacion_salarial",
    "que_tan_conforme_estas_con_tus_ingresos_laborales": "satisfaccion_ingresos",
    "estas_buscando_trabajo": "buscando_trabajo",
    "trabajo_de": "puesto",
    "anos_de_experiencia": "anios_experiencia",
    "antiguedad_empresa": "antiguedad_empresa",
    "antiguedad_en_la_empresa_actual": "antiguedad_empresa",
    "tiempo_en_el_puesto_actual": "tiempo_puesto",
    "modalidad_de_trabajo": "modalidad",
    "si_trabajas_bajo_un_esquema_hibrido_cuantos_dias_a_la_semana_vas_a_la_oficina": "dias_presenciales",
    "nivel_estudios": "nivel_estudios",
    "maximo_nivel_de_estudios": "nivel_estudios",
    "tenes_guardias": "guardias"
}

In [4]:
# Aplicamos renombrado
df1 = df1.rename(columns=renombre_col)
df2 = df2.rename(columns=renombre_col)

In [5]:
#Ignoramos el pais ya que es encuesta de Argentina
df1 = df1.drop(columns=["estoy_trabajando_en"], errors="ignore")
df2 = df2.drop(columns=["estoy_trabajando_en"], errors="ignore")
#Eliminamos columnas duplicadas que puedan haber quedado por casualidad
df1 = df1.loc[:, ~df1.columns.duplicated()]
df2 = df2.loc[:, ~df2.columns.duplicated()]

In [6]:
#Revisamos
print("Columnas DF1:", df1.columns.tolist())
print("Columnas DF2:", df2.columns.tolist())

Columnas DF1: ['provincia', 'jornada', 'tipo_contrato', 'ultimo_salario_mensual_o_retiro_bruto_en_tu_moneda_local', 'salario_neto_ars', 'pagos_en_dolares', 'valor_dolar', 'pagos_en_criptomonedas', 'que_porcentaje_o_monto_recibis_en_criptomonedas', 'bono', 'a_que_esta_atado_el_bono', 'actualizacion_salarial', 'de_que_fue_el_ajuste_total_acumulado', 'en_que_mes_fue_el_ultimo_ajuste', 'como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior', 'con_que_beneficios_contas', 'satisfaccion_ingresos', 'buscando_trabajo', 'puesto', 'anios_experiencia', 'antiguedad_empresa', 'tiempo_puesto', 'cuantas_personas_a_cargo_tenes', 'plataformas_que_utilizas_en_tu_puesto_actual', 'lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual', 'frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual', 'bases_de_datos', 'qa_testing', 'cantidad_de_personas_en_tu_organizacion', 'modalidad', 'dias_presenciales', 'la_recomendas_como_un_buen_lugar_para_trabajar', 'salir_o_seguir_contestando', 'nivel_estudios', 'estado', 'carrera', 'universidad', 'participaste_de_algun_boot_camp', 'si_participaste_de_un_boot_campque_carrera_estudiaste', 'salir_o_seguir_contestando_sobre_las_guardias', 'guardias', 'cuanto_cobras_por_guardia', 'porcentajebruto_o_neto', 'salir_o_seguir_contestando_sobre_estudios', 'edad', 'genero', 'sueldo_dolarizado', 'seniority', 'me_id_extra']
Columnas DF2: ['provincia', 'jornada', 'tipo_contrato', 'ultimo_salario_mensual_o_retiro_bruto_en_tu_moneda_local', 'salario_neto_ars', 'pagos_en_dolares', 'valor_dolar', 'bono', 'a_que_esta_atado_el_bono', 'actualizacion_salarial', 'de_que_fue_el_ajuste_total_acumulado', 'en_que_mes_fue_el_ultimo_ajuste', 'como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior', 'contas_con_beneficios_adicionales', 'satisfaccion_ingresos', 'buscando_trabajo', 'puesto', 'anios_experiencia', 'antiguedad_empresa', 'tiempo_puesto', 'cuantas_personas_a_cargo_tenes', 'plataformas_que_utilizas_en_tu_puesto_actual', 'lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual', 'frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual', 'bases_de_datos', 'qa_testing', 'cantidad_de_personas_en_tu_organizacion', 'modalidad', 'dias_presenciales', 'la_recomendas_como_un_buen_lugar_para_trabajar', 'que_tanto_estas_usando_copilotchatgpt_u_otras_herramientas_de_ia_para_tu_trabajo', 'salir_o_seguir_contestando', 'nivel_estudios', 'estado', 'carrera', 'institucion_educativa', 'salir_o_seguir_contestando_sobre_las_guardias', 'guardias', 'cuanto_cobras_por_guardia', 'aclara_el_numero_que_ingresaste_en_el_campo_anterior', 'salir_o_seguir_contestando_sobre_estudios', 'edad', 'genero', 'sueldo_dolarizado', 'seniority', '_sal']

In [7]:
#tomamos las columnas finales
columnas_finales = [
    "provincia", "jornada", "tipo_contrato", "salario_neto_ars",
    "sueldo_dolarizado", "valor_dolar", "edad", "genero", "seniority",
    "bono", "actualizacion_salarial", "satisfaccion_ingresos", "buscando_trabajo",
    "puesto", "anios_experiencia", "antiguedad_empresa", "tiempo_puesto",
    "modalidad", "dias_presenciales", "nivel_estudios", "guardias"
]

df1 = df1[[c for c in columnas_finales if c in df1.columns]]
df2 = df2[[c for c in columnas_finales if c in df2.columns]]

In [8]:
#concatenamos las filas que nos quedaron
df = pd.concat([df1, df2], ignore_index=True)
print("Filas unificadas:", len(df))
print("Columnas finales:", df.columns.tolist())

Filas unificadas: 11189
Columnas finales: ['provincia', 'jornada', 'tipo_contrato', 'salario_neto_ars', 'sueldo_dolarizado', 'valor_dolar', 'edad', 'genero', 'seniority', 'bono', 'actualizacion_salarial', 'satisfaccion_ingresos', 'buscando_trabajo', 'puesto', 'anios_experiencia', 'antiguedad_empresa', 'tiempo_puesto', 'modalidad', 'dias_presenciales', 'nivel_estudios', 'guardias']

In [9]:
#revisamos
print("Shape:", df.shape)
display(df.head(10))

Shape: (11189, 21)

,provincia,jornada,tipo_contrato,salario_neto_ars,sueldo_dolarizado,valor_dolar,edad,genero,seniority,bono,...,satisfaccion_ingresos,buscando_trabajo,puesto,anios_experiencia,antiguedad_empresa,tiempo_puesto,modalidad,dias_presenciales,nivel_estudios,guardias
0,Buenos Aires,Full-Time,Staff (planta permanente),396346,False,None,25,Varón Cis,Semi-Senior,Menos de un sueldo,...,4,"No, estoy muy conforme.",Developer,3.0,0.0,0.0,100% remoto,0,None,None
1,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),220000,False,None,27,Mujer Cis,Junior,No,...,2,"No, pero escucho ofertas.",Developer,2.0,1.0,1.0,100% remoto,0,None,None
2,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),88560,False,None,21,Varón Cis,Junior,No,...,2,"No, pero escucho ofertas.",Developer,0.0,0.0,0.0,Híbrido (presencial y remoto),1,None,None
3,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),283700,False,None,25,Varón Cis,Semi-Senior,Un sueldo,...,2,"No, estoy muy conforme.",Developer,3.0,1.0,1.0,100% remoto,0,Universitario,No
4,Río Negro,Full-Time,Staff (planta permanente),320000,True,179,24,Varón Cis,Junior,Un sueldo,...,4,"No, estoy muy conforme.",Developer,0.0,0.0,0.0,100% remoto,0,None,None
5,Córdoba,Full-Time,Staff (planta permanente),205000,False,None,38,Mujer Cis,Senior,No,...,4,"No, pero escucho ofertas.",Product Manager,12.0,1.0,1.0,100% remoto,0,Terciario,None
6,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),1200000,True,314,37,Varón Cis,Senior,No,...,3,"No, pero escucho ofertas.",Technical Leader,19.0,4.0,1.0,100% remoto,0,Universitario,No
7,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),610000,False,170,28,Varón Cis,Senior,No,...,4,"Sí, estoy buscando activamente.",Technical Leader,7.0,2.0,2.0,100% remoto,0,Universitario,No
8,Mendoza,Full-Time,Staff (planta permanente),800000,False,None,28,Varón Cis,Semi-Senior,No,...,4,"No, pero escucho ofertas.",Developer,5.0,0.0,0.0,Híbrido (presencial y remoto),1,Terciario,No
9,Córdoba,Full-Time,Staff (planta permanente),450000,False,None,39,Varón Cis,Senior,3+ sueldos,...,4,"No, pero escucho ofertas.",DBA,13.0,2.0,2.0,100% remoto,0,None,"Sí, pasiva"

In [10]:
#revisamos informacion
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11189 entries, 0 to 11188
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   provincia               11189 non-null  object
 1   jornada                 11189 non-null  object
 2   tipo_contrato           11189 non-null  object
 3   salario_neto_ars        10769 non-null  object
 4   sueldo_dolarizado       11189 non-null  bool
 5   valor_dolar             2101 non-null   object
 6   edad                    11189 non-null  object
 7   genero                  11189 non-null  object
 8   seniority               11189 non-null  object
 9   bono                    11189 non-null  object
 10  actualizacion_salarial  11189 non-null  object
 11  satisfaccion_ingresos   11189 non-null  int64
 12  buscando_trabajo        11189 non-null  object
 13  puesto                  11189 non-null  object
 14  anios_experiencia       11189 non-null  float64
 15  antiguedad_empresa      11189 non-null  float64
 16  tiempo_puesto           11189 non-null  float64
 17  modalidad               11189 non-null  object
 18  dias_presenciales       11189 non-null  int64
 19  nivel_estudios          5111 non-null   object
 20  guardias                3389 non-null   object
dtypes: bool(1), float64(3), int64(2), object(15)
memory usage: 1.7+ MB

In [11]:
print("Número de filas:", len(df))

Número de filas: 11189

In [12]:
# Recorremos todas las columnas y mostramos valores únicos (30 por columna para revisar) y contamos el total de los valores unicos para tener unamejor perspectiva de los datos
for col in df.columns:
    print(f"\n Columna: {col}")
    print(df[col].unique()[:30])
    print("Valores únicos:", df[col].nunique())
    print("-----------------------------------------------------------------")

 Columna: provincia
['Buenos Aires' 'Ciudad Autónoma de Buenos Aires' 'Río Negro' 'Córdoba'
 'Mendoza' 'San Luis' 'Jujuy' 'Entre Ríos' 'Tierra del Fuego' 'Santa Fe'
 'Chaco' 'San Juan' 'Chubut' 'Corrientes' 'Misiones' 'Neuquén' 'Salta'
 'Tucumán' 'La Rioja' 'Santa Cruz' 'La Pampa' 'Formosa'
 'Santiago del Estero' 'Catamarca']
Valores únicos: 24
-----------------------------------------------------------------

 Columna: jornada
['Full-Time' 'Part-Time']
Valores únicos: 2
-----------------------------------------------------------------

 Columna: tipo_contrato
['Staff (planta permanente)' 'Remoto (empresa de otro país)'
 'Tercerizado (trabajo a través de consultora o agencia)' 'Freelance'
 'Participación societaria en una cooperativa' 'Contractor']
Valores únicos: 6
-----------------------------------------------------------------

 Columna: salario_neto_ars
['396346' '220000' '88560' '283700' '320000' '205000' '1200000' '610000'
 '800000' '450000' '302000' '633000' '1500000' '161400' '76000' '277000'
 '260000' '160000' '163457' '100000' '319000' '252000' '281000' '220500'
 '290000' '313000' '934000' None '400000' '144000']
Valores únicos: 3453
-----------------------------------------------------------------

 Columna: sueldo_dolarizado
[False  True]
Valores únicos: 2
-----------------------------------------------------------------

 Columna: valor_dolar
[None '179' '314' '170' '156' '171' 'No cobro en usd'
 'Dólar banco nación.' 'Ninguno, me pagan en dólares en el exterior' '168'
 '311' '165' '160' '310' '163' '161' 'No' '169' '330' '280' '315' '0'
 '318' '305' '4000' 'Oficial' '295' '313' '159,10' 'dolar oficial']
Valores únicos: 563
-----------------------------------------------------------------

 Columna: edad
['25' '27' '21' '24' '38' '37' '28' '39' '26' '22' '40' '23' '29' '42'
 '32' '41' '35' '36' '34' '30' '33' '31' '45' '48' '44' '30-40' '47' '43'
 '49' '50']
Valores únicos: 123
-----------------------------------------------------------------

 Columna: genero
['Varón Cis' 'Mujer Cis' 'Masculino.' 'Hombre' 'Bigénero' 'Varón'
 'Prefiero no decir' 'Macho lomo plateado' 'Mujer' 'Macho Argentino'
 'Hombre heterosexual' 'Normal' 'Masculino' 'Cis' 'Varón Trans'
 'No me identifico con nada, soy un hombre normal'
 'Boeing B-17 Flying Fortress' 'Fluido' 'No binarie' 'Soy un hombre'
 'Queer' 'Soy VARÓN... no se entienden algunas opciones (?)' 'normal'
 'hombre' 'Esto es una pelotudez' 'Pregunta irrelevante' 'Agénero'
 'MASCULINO (CORTA LA BOCHA)' 'Helicóptero Apache' 'masculino']
Valores únicos: 127
-----------------------------------------------------------------

 Columna: seniority
['Semi-Senior' 'Junior' 'Senior']
Valores únicos: 3
-----------------------------------------------------------------

 Columna: bono
['Menos de un sueldo' 'No' 'Un sueldo' '3+ sueldos'
 'De uno a tres sueldos']
Valores únicos: 5
-----------------------------------------------------------------

 Columna: actualizacion_salarial
['Uno' 'Tres' 'No' 'Más de tres' 'Dos']
Valores únicos: 5
-----------------------------------------------------------------

 Columna: satisfaccion_ingresos
[4 2 3 1]
Valores únicos: 4
-----------------------------------------------------------------

 Columna: buscando_trabajo
['No, estoy muy conforme.' 'No, pero escucho ofertas.'
 'Sí, estoy buscando activamente.']
Valores únicos: 3
-----------------------------------------------------------------

 Columna: puesto
['Developer' 'Product Manager' 'Technical Leader' 'DBA'
 'SysAdmin / DevOps / SRE' 'Soporte L2/L3' 'Data Engineer'
 'Recruiter / HR' 'Project Manager' 'Consultant' 'Data Scientist'
 'Marketing Manager' 'Manager / Director' 'HelpDesk' 'Architect' 'Infosec'
 'BI Analyst / Data Analyst' 'Networking' 'Head of Data & Analytics'
 'Business Analyst' 'UX Designer' 'QA / Tester' 'Key account manager'
 'IT Governance Head' 'Ecommerce Manager' 'Automation Tester' 'Middleware'
 'AV tech' 'Coordinador TI' 'FullStack']
Valores únicos: 502
-----------------------------------------------------------------

 Columna: anios_experiencia
[ 3.   2.   0.  12.  19.   7.   5.  13.   1.   6.   1.5  4.  20.  15.
 17.  18.  10.   8.  16.  14.  25.  34.   2.5 21.   9.  27.   3.5 30.
 11.  22. ]
Valores únicos: 61
-----------------------------------------------------------------

 Columna: antiguedad_empresa
[ 0.   1.   4.   2.   5.   1.5  3.   7.   0.6 11.   6.  10.  18.  13.
  0.5 15.   2.5 12.  30.  16.  14.  19.   8.  21.  25.   9.  20.   1.8
 26.   1.4]
Valores únicos: 54
-----------------------------------------------------------------

 Columna: tiempo_puesto
[ 0.   1.   2.   1.5  3.   8.   4.   0.6  5.   6.  15.   7.  11.   0.5
 10.   2.5  3.5 20.  14.   9.  12.  16.   1.8 26.  17.   1.4  0.4 13.
  1.7 22. ]
Valores únicos: 49
-----------------------------------------------------------------

 Columna: modalidad
['100% remoto' 'Híbrido (presencial y remoto)' '100% presencial']
Valores únicos: 3
-----------------------------------------------------------------

 Columna: dias_presenciales
[0 1 3 2 4 5]
Valores únicos: 6
-----------------------------------------------------------------

 Columna: nivel_estudios
[None 'Universitario' 'Terciario' 'Secundario' 'Posgrado/Especialización'
 'Maestría' 'Doctorado' 'Posdoctorado']
Valores únicos: 7
-----------------------------------------------------------------

 Columna: guardias
[None 'No' 'Sí, pasiva' 'Sí, activa']
Valores únicos: 3
-----------------------------------------------------------------

Limpieza de las columnas

In [13]:
import unidecode
import numpy as np

In [14]:
def limpiar_provincia(df, col="provincia"):
    df = df.copy()
    # Unificamos CABA y PVBA en Buenos Aires
    df[col] = df[col].replace({
        "Ciudad Autónoma de Buenos Aires": "Buenos Aires",
        "Provincia de Buenos Aires": "Buenos Aires"
    })

    #mapeamos a ids
    mapping = {
        "Buenos Aires": 1,
        "Córdoba": 2,
        "Río Negro": 3,
        "Mendoza": 4,
        "San Luis": 5,
        "Jujuy": 6,
        "Entre Ríos": 7,
        "Tierra del Fuego": 8,
        "Santa Fe": 9,
        "Chaco": 10,
        "San Juan": 11,
        "Chubut": 12,
        "Corrientes": 13,
        "Misiones": 14,
        "Neuquén": 15,
        "Salta": 16,
        "Tucumán": 17,
        "La Rioja": 18,
        "Santa Cruz": 19,
        "La Pampa": 20,
        "Formosa": 21,
        "Santiago del Estero": 22,
        "Catamarca": 23
    }

    df[col] = df[col].map(mapping)
    return df, mapping

In [15]:
def limpiar_jornada(df, col="jornada"):
    df = df.copy()
    mapping = {"Full-Time": 1, "Part-Time": 2}
    df[col] = df[col].map(mapping)
    return df, mapping

In [16]:
def limpiar_tipo_contrato(df, col="tipo_contrato"):
    df = df.copy()
    mapping = {
    "Staff (planta permanente)": 1,
    "Remoto (empresa de otro país)": 2,
    "Tercerizado (trabajo a través de consultora o agencia)": 3,
    "Freelance": 4,
    "Participación societaria en una cooperativa": 5,
    "Contractor": 6
}
    df[col] = df[col].map(mapping)
    return df, mapping

In [17]:
def limpiar_salario(df, col="salario_neto_ars"):
    df = df.copy()
    df[col] = pd.to_numeric(df[col], errors="coerce")
    return df

In [18]:
def limpiar_sueldo_dolarizado(df, col="sueldo_dolarizado"):
    df = df.copy()

    def normalizar(x):
        if pd.isna(x):
            return np.nan
        texto = str(x).strip().lower()

        # Si dolarizado
        if texto in ["si", "sí", "true", "1"]:
            return 1
        if "usd" in texto or "dólar" in texto or "dolar" in texto:
            return 1  #para evitar perder valores del dolar buscamos palabras o frases que contengan para setearlo como 1

        # No dolarizado
        if texto in ["no", "false", "2"]:
            return 2
        if "no" in texto or "ninguno" in texto:
            return 2  #Por si escribieron no cobro en dolares o cosas así

        return np.nan  # valores no reconocidos quedan como nulos(usar la posible solucion)
    df[col] = df[col].apply(normalizar)
    mapping = {"Sí dolarizado": 1, "No dolarizado": 2}
    return df, mapping

In [19]:
def limpiar_valor_dolar(df, col="valor_dolar"):
    df = df.copy()
    
    # Solo registros dolarizados osea que tienen marcado Si o devuelven 1
    mask_dolarizado = df['sueldo_dolarizado'] == 1
    
    def parse_dolar(x):
        try:
            if pd.isna(x) or x == "":
                return np.nan
            
            import re
            texto = str(x)
            
            # Buscar números en el texto (incluyendo decimales) para evitar perder datos útiles ya que algunos pusieron blue 1200 o parecido
            numeros = re.findall(r'\d+[.,]?\d*', texto)
            
            if numeros:
                # Tomar el primer número encontrado
                numero_str = numeros[0].replace(',', '.')
                valor = float(numero_str)
                
                # configuramos un rango valido en argentina para el valor dolar
                if 50 <= valor <= 1400:
                    return valor
            
            return np.nan
        except:
            return np.nan
    
    #Aplicamos el parseo de dolar para LOS QUE CUMPLAN EL FILTRO DE Q PUSIERON Q SI
    df.loc[mask_dolarizado, col] = df.loc[mask_dolarizado, col].apply(parse_dolar)
    
    # Dejamos los no como nulos
    df.loc[~mask_dolarizado, col] = np.nan
    
    return df

In [20]:
def limpiar_edad(df, col="edad"):
    df = df.copy()
    
    def parse_edad(x):
        try:
            if pd.isna(x):
                return np.nan
            
            # Si viene como rango ejemplo: "30-40", tomar el primer valor y listo(explicar porque)
            edad_str = str(x).split("-")[0]
            edad = float(edad_str)
            
            # Validamos un rango para no tener datos de +80 años o menores de 16(por las dudas)
            if 16 <= edad <= 80:
                return edad
            
            return np.nan
        except:
            return np.nan
    
    df[col] = df[col].apply(parse_edad)
    return df

In [21]:
def limpiar_genero(df, col="genero"):
    df = df.copy()
    mapping = {"Hombre": 1, "Mujer": 2, "No especificado": 3}
    def map_genero(x):
        val = unidecode.unidecode(str(x)).lower()
        if "hombre" in val or "varon" in val or "masculino" in val:
            return mapping["Hombre"]
        elif "mujer" in val or "femenino" in val:
            return mapping["Mujer"]
        else:
            return mapping["No especificado"]
    df[col] = df[col].apply(map_genero)
    return df, mapping

In [22]:
def limpiar_bono(df, col="bono"):
    df = df.copy()
    mapping = {"Si": 1, "No": 2}
    df[col] = df[col].apply(lambda x: 1 if "no" not in str(x).lower() else 2)
    return df, mapping

In [23]:
def limpiar_seniority(df, col="seniority"):
    df = df.copy()
    mapping = {"Junior": 1, "Semi-Senior": 2, "Senior": 3}
    df[col] = df[col].map(mapping)
    return df, mapping

In [24]:

def limpiar_actualizacion_salarial(df, col="actualizacion_salarial"):
    df = df.copy()
    mapping = {"Si": 1, "No": 2}
    df[col] = df[col].apply(lambda x: 1 if "no" not in str(x).lower() else 2)
    return df, mapping

In [ ]:
def limpiar_satisfaccion_ingresos(df, col="satisfaccion_ingresos"):
    df = df.copy()
    
    # Mapeo más amplio basado en números ( ya vienen como 1,2,3,4)
    def map_satisfaccion(x):
        try:
            val = int(float(x))
            if 1 <= val <= 4:
                return val
            return 4  # Default a "Muy conforme" si está fuera de rango
        except:
            return 4  # Default si no se puede convertir
    
    df[col] = df[col].apply(map_satisfaccion)
    
    mapping = { "Muy disconforme": 1, "Disconforme": 2, "Conforme": 3, "Muy conforme": 4}
    return df, mapping

In [26]:
def limpiar_buscando_trabajo(df, col="buscando_trabajo"):
    df = df.copy()
        
    mapping = {
        "Sí, estoy buscando activamente.": 1,
        "No, estoy muy conforme.": 2,
        "No, pero escucho ofertas.": 3
    }
    
    # Función de mapeo más amplia
    def map_buscando(x):
        if pd.isna(x):
            return 3
        
        x_str = str(x).lower()
        if "buscando activamente" in x_str or "sí" in x_str:
            return 1
        elif "muy conforme" in x_str:
            return 2
        else:
            return 3
    
    df[col] = df[col].apply(map_buscando)
    return df, mapping

In [27]:
def mapear_puesto(df, col="puesto"):
    df = df.copy()
    mapping = {
        "Desarrollador": 1,
        "Data": 2,
        "QA": 3,
        "Infraestructura": 4,
        "Management": 5,
        "RRHH": 6,
        "Otros": 7
    }

    grupos = {
        "Developer": mapping["Desarrollador"],
        "Fullstack": mapping["Desarrollador"],
        "Technical Leader": mapping["Management"],
        "Product Manager": mapping["Management"],
        "Project Manager": mapping["Management"],
        "Manager / Director": mapping["Management"],
        "Recruiter / HR": mapping["RRHH"],
        "QA / Tester": mapping["QA"],
        "Sysadmin / Devops / Sre": mapping["Infraestructura"],
        "Data Engineer": mapping["Data"],
        "Data Scientist": mapping["Data"],
        "Bi Analyst / Data Analyst": mapping["Data"]
    }

    def map_func(x):
        return grupos.get(str(x), mapping["Otros"])

    df[col] = df[col].apply(map_func)
    return df, mapping

In [28]:
def limpiar_experiencia_antiguedad(df):
    df = df.copy()
    for col in ["anios_experiencia", "antiguedad_empresa", "tiempo_puesto"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")
        df[col] = df[col].fillna(0).round().astype(int)
    return df

In [29]:
def limpiar_modalidad_dias(df, col="modalidad"):
    
    df = df.copy()
    mapping = {"Remoto": 1, "Hibrido": 2, "Presencial": 3}
    
    def map_modalidad(x):
        val = unidecode.unidecode(str(x)).lower()
        
        # PRIMERO híbrido (más específico) ya si ponemos remoto hay 2 opciones que contienen esa palabra
        if "hibrid" in val:
            return mapping["Hibrido"]
        elif "remoto" in val:
            return mapping["Remoto"]
        elif "presencial" in val:
            return mapping["Presencial"]
        else:
            return np.nan
    
    df[col] = df[col].apply(map_modalidad)
    
    # Ajustamos días presenciales según modalidad
    df.loc[df[col] == mapping["Remoto"], "dias_presenciales"] = 0
    df.loc[df[col] == mapping["Presencial"], "dias_presenciales"] = 5
    
    return df, mapping

In [30]:
def limpiar_nivel_estudios(df, col="nivel_estudios"):
    df = df.copy()
    mapping = {
        "Secundario": 1,
        "Terciario": 2,
        "Universitario": 3,
        "Posgrado/Especialización": 4,
        "Maestría": 5,
        "Doctorado": 6,
        "Posdoctorado": 7,
        "No especificado": 8
    }
    
    
    # Convertir None/NaN a "No especificado"
    df[col] = df[col].fillna("No especificado")
    
    # Función para mapeo seguro
    def map_estudios(x):
        if x in mapping:
            return mapping[x]
        
        # Buscar por similitud limpiando los acentos y pasando a minúsculas, forma más facil de filtrar sin perder datos
        x_clean = unidecode.unidecode(str(x)).lower()
        for key, value in mapping.items():
            key_clean = unidecode.unidecode(key).lower()
            if key_clean in x_clean or x_clean in key_clean:
                return value
        
        return mapping["No especificado"]
    
    df[col] = df[col].apply(map_estudios)
    
    return df, mapping

In [31]:
def limpiar_guardias(df, col="guardias"):
    df = df.copy()
    mapping = {"No": 3, "Si, Pasiva": 1, "Si, Activa": 2}
    
    def map_guardias(x):
        if x is None or str(x).lower() == "no":
            return mapping["No"]
        elif "pasiva" in str(x).lower():
            return mapping["Si, Pasiva"]
        elif "activa" in str(x).lower():
            return mapping["Si, Activa"]
        return mapping["No"]
    
    df[col] = df[col].apply(map_guardias)
    return df, mapping

In [32]:
def verificar_y_limpiar_nans_final(df):
    #Limpieza final: elimina registros con NaN en columnas críticas. nos devuelve el DataFrame limpio esto para que no se filtren datos.
    # Columnas críticas que NO pueden tener NaN
    columnas_criticas = ['salario_neto_ars', 'edad']
    #Eliminamos los nulos de las columnas criticas
    df = df.dropna(subset=columnas_criticas)
    return df

In [33]:
def limpiar_silver(df):
    mappings = {}
    #los que tienen numericos es porque no necesitan mapping
    df, mappings["provincia"] = limpiar_provincia(df)
    df, mappings["jornada"] = limpiar_jornada(df)
    df, mappings["tipo_contrato"] = limpiar_tipo_contrato(df)
    df = limpiar_salario(df)
    df, mappings["sueldo_dolarizado"] = limpiar_sueldo_dolarizado(df)
    df = limpiar_valor_dolar(df)
    df = limpiar_edad(df) 
    df, mappings["genero"] = limpiar_genero(df)
    df, mappings["seniority"] = limpiar_seniority(df) 
    df, mappings["bono"] = limpiar_bono(df)
    df, mappings["actualizacion_salarial"] = limpiar_actualizacion_salarial(df)
    df, mappings["satisfaccion_ingresos"] = limpiar_satisfaccion_ingresos(df)
    df, mappings["buscando_trabajo"] = limpiar_buscando_trabajo(df)
    df, mappings["puesto"] = mapear_puesto(df)
    df = limpiar_experiencia_antiguedad(df)
    df, mappings["modalidad"] = limpiar_modalidad_dias(df)
    df, mappings["nivel_estudios"] = limpiar_nivel_estudios(df)
    df, mappings["guardias"] = limpiar_guardias(df)
    df = verificar_y_limpiar_nans_final(df)

    return df, mappings

In [34]:
df_silver, mappings = limpiar_silver(df)

df_silver.head()

,provincia,jornada,tipo_contrato,salario_neto_ars,sueldo_dolarizado,valor_dolar,edad,genero,seniority,bono,...,satisfaccion_ingresos,buscando_trabajo,puesto,anios_experiencia,antiguedad_empresa,tiempo_puesto,modalidad,dias_presenciales,nivel_estudios,guardias
0,1,1,1,396346.0,2,NaN,25.0,1,2,2,...,4,2,1,3,0,0,1,0,8,3
1,1,1,1,220000.0,2,NaN,27.0,2,1,2,...,2,3,1,2,1,1,1,0,8,3
2,1,1,1,88560.0,2,NaN,21.0,1,1,2,...,2,3,1,0,0,0,2,1,8,3
3,1,1,1,283700.0,2,NaN,25.0,1,2,1,...,2,2,1,3,1,1,1,0,3,3
4,3,1,1,320000.0,1,179.0,24.0,1,1,1,...,4,2,1,0,0,0,1,0,8,3

In [35]:
#Renombrar para que no haya confusion con las tablas auxiliares que vamos a crear
renombrar_ids = {
    "provincia": "id_provincia",
    "jornada": "id_jornada",
    "tipo_contrato": "id_tipo_contrato",
    "sueldo_dolarizado": "id_sueldo_dolarizado",
    "genero": "id_genero",
    "seniority": "id_seniority",
    "bono": "id_bono",
    "actualizacion_salarial": "id_actualizacion_salarial",
    "satisfaccion_ingresos": "id_satisfaccion_ingresos",
    "buscando_trabajo": "id_buscando_trabajo",
    "puesto": "id_puesto",
    "modalidad": "id_modalidad",
    "nivel_estudios": "id_nivel_estudios",
    "guardias": "id_guardias"
}

df_silver = df_silver.rename(columns=renombrar_ids)

In [36]:
#verificamos el cambio de nombre
df_silver.head()

,id_provincia,id_jornada,id_tipo_contrato,salario_neto_ars,id_sueldo_dolarizado,valor_dolar,edad,id_genero,id_seniority,id_bono,...,id_satisfaccion_ingresos,id_buscando_trabajo,id_puesto,anios_experiencia,antiguedad_empresa,tiempo_puesto,id_modalidad,dias_presenciales,id_nivel_estudios,id_guardias
0,1,1,1,396346.0,2,NaN,25.0,1,2,2,...,4,2,1,3,0,0,1,0,8,3
1,1,1,1,220000.0,2,NaN,27.0,2,1,2,...,2,3,1,2,1,1,1,0,8,3
2,1,1,1,88560.0,2,NaN,21.0,1,1,2,...,2,3,1,0,0,0,2,1,8,3
3,1,1,1,283700.0,2,NaN,25.0,1,2,1,...,2,2,1,3,1,1,1,0,3,3
4,3,1,1,320000.0,1,179.0,24.0,1,1,1,...,4,2,1,0,0,0,1,0,8,3

In [37]:
#Creamos el csv final
df_silver.to_csv("Data/Silver/encuesta_silver.csv", index=False, encoding="utf-8")

In [38]:

def crear_tabla_genero(mapping, conn, schema="Silver"):
    cursor = conn.cursor()

    #con cursor ejecutamos el comando para crear la tabla e insertamos los valores del mapping que devuelve la funcioN
    cursor.execute(f"""
    CREATE TABLE {schema}.TBL_GENERO (
        ID INT PRIMARY KEY,
        DESCRIPCION NVARCHAR(100) NOT NULL
    );
    """)

    #Insertamos los valores del mapping que devuelve la funcion
    for desc, id_val in mapping.items():
        cursor.execute(
            f"INSERT INTO {schema}.TBL_GENERO (ID, DESCRIPCION) VALUES (?, ?)",
            id_val, desc
        )
    #Hacemos el commit o "guardamos"...
    conn.commit()

In [39]:
# Tomamos el mapping de género que salió de limpiar_silver
df_silver, mappings = limpiar_silver(df)
#Tomamos el mapping devuelto por la funcion DE GENERO, lo PASAMOS como parametro ya que la funcion limpiar_silver devuelve el df y el mapping, pasamos tambien la conexion y el schema
crear_tabla_genero(mappings["genero"], conn, schema="Silver")

Comentar que si nosotros tenemos el mapping podriamos crear una funcion para que se creen las tablas solas en base a los mappings que ya tenemos, mas que nada para evitar escribir cursor excute muchas veces y los valores..
(Mostrar el lunes, anotacion es esto)

In [40]:
mapping_provincia = mappings["provincia"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_PROVINCIA', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_PROVINCIA;

CREATE TABLE Silver.TBL_PROVINCIA (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
""")

for desc, id_val in mapping_provincia.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_PROVINCIA (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [41]:
#Tipo de contrato
# 1) Obtenemos el mapping de contrato desde lo que devolvió limpiar_silver
df_silver, mappings = limpiar_silver(df)
mapping_contrato = mappings["tipo_contrato"]

# 2) Creamos un cursor
cursor = conn.cursor()

# 3) Si la tabla existe la borramos (opcional, para evitar error)
cursor.execute("""
IF OBJECT_ID('Silver.TBL_CONTRATO', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_CONTRATO;

CREATE TABLE Silver.TBL_CONTRATO (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
""")

# 4) Insertamos los valores del mapping en la tabla
for desc, id_val in mapping_contrato.items():
        cursor.execute(
            "INSERT INTO Silver.TBL_CONTRATO (ID, DESCRIPCION) VALUES (?, ?)",
            id_val, desc
        )

# 5) Guardamos cambios
conn.commit()

In [42]:
mapping_seniority = mappings["seniority"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_SENIORITY', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_SENIORITY;

CREATE TABLE Silver.TBL_SENIORITY (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
""")

for desc, id_val in mapping_seniority.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_SENIORITY (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [43]:
mapping_jornada = mappings["jornada"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_JORNADA', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_JORNADA;

CREATE TABLE Silver.TBL_JORNADA (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
""")

for desc, id_val in mapping_jornada.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_JORNADA (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [44]:
mapping_modalidad = mappings["modalidad"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_MODALIDAD', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_MODALIDAD;

CREATE TABLE Silver.TBL_MODALIDAD (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
""")

for desc, id_val in mapping_modalidad.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_MODALIDAD (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [45]:
mapping_estudios = mappings["nivel_estudios"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_ESTUDIOS', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_ESTUDIOS;

CREATE TABLE Silver.TBL_ESTUDIOS (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
""")

for desc, id_val in mapping_estudios.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_ESTUDIOS (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [46]:
mapping_sueldo_dolarizado = mappings["sueldo_dolarizado"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_SUELDO_DOLARIZADO', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_SUELDO_DOLARIZADO;

CREATE TABLE Silver.TBL_SUELDO_DOLARIZADO (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(50) NOT NULL
);
""")

for desc, id_val in mapping_sueldo_dolarizado.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_SUELDO_DOLARIZADO (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [47]:
mapping_bono = mappings["bono"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_BONO', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_BONO;

CREATE TABLE Silver.TBL_BONO (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(50) NOT NULL
);
""")

for desc, id_val in mapping_bono.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_BONO (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [48]:
mapping_actualizacion = mappings["actualizacion_salarial"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_ACTUALIZACION_SALARIAL', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_ACTUALIZACION_SALARIAL;

CREATE TABLE Silver.TBL_ACTUALIZACION_SALARIAL (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(50) NOT NULL
);
""")

for desc, id_val in mapping_actualizacion.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_ACTUALIZACION_SALARIAL (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [49]:
mapping_satisfaccion = mappings["satisfaccion_ingresos"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_SATISFACCION_INGRESOS', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_SATISFACCION_INGRESOS;

CREATE TABLE Silver.TBL_SATISFACCION_INGRESOS (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
""")

for desc, id_val in mapping_satisfaccion.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_SATISFACCION_INGRESOS (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

DataError: ('22018', "[22018] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value 'Muy disconforme' to data type int. (245) (SQLExecDirectW)")

In [ ]:
mapping_buscando = mappings["buscando_trabajo"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_BUSCANDO_TRABAJO', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_BUSCANDO_TRABAJO;

CREATE TABLE Silver.TBL_BUSCANDO_TRABAJO (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(50) NOT NULL
);
""")

for desc, id_val in mapping_buscando.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_BUSCANDO_TRABAJO (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [ ]:
mapping_puesto = mappings["puesto"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_PUESTO', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_PUESTO;

CREATE TABLE Silver.TBL_PUESTO (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(150) NOT NULL
);
""")

for desc, id_val in mapping_puesto.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_PUESTO (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()

In [ ]:
mapping_guardias = mappings["guardias"]

cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Silver.TBL_GUARDIAS', 'U') IS NOT NULL
    DROP TABLE Silver.TBL_GUARDIAS;

CREATE TABLE Silver.TBL_GUARDIAS (
    ID INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(50) NOT NULL
);
""")

for desc, id_val in mapping_guardias.items():
    cursor.execute(
        "INSERT INTO Silver.TBL_GUARDIAS (ID, DESCRIPCION) VALUES (?, ?)",
        id_val, desc
    )

conn.commit()